# Generated by Django 2.1.5 on 2019-03-30 23:02

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invite', models.CharField(max_length=200)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('timeout', models.DurationField(default=datetime.timedelta(0, 120))),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Game')),
            ],
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=200)),
                ('freq', models.FloatField()),
                ('length', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='player',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Team'),
        ),
        migrations.AddField(
            model_name='player',
            name='word',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='polls.Word'),
        ),
        migrations.AddField(
            model_name='game',
            name='master',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Player'),
        ),
        migrations.AddField(
            model_name='game',
            name='target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='polls.Word'),
        ),
    ]
