# Generated by Django 2.1.7 on 2019-03-31 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20190331_0406'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='state',
            field=models.IntegerField(default=0),
        ),
    ]
